name: azure_cognitive
channels:
  - defaults
dependencies:
  - python=3.7.3
  - pip=19.1.1
  - python-dateutil=2.8.0
  - pip:
    - azure-ai-textanalytics
    - azure-cognitiveservices-vision-computervision
    - azure-cognitiveservices-vision-customvision
    - matplotlib
    - numpy
    - pillow
    - python-dotenv